language: python
python:
  - 3.6

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - id
  - mv controv3rsial.conf /etc/supervisor/conf.d
  - pip install --upgrade pytest
  - supervisorctl reread
  - supervisorctl reload

script: pytest

