language: python
sudo: required
python:
  - 3.6

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - id
  - pwd
  - sudo apt-get install supervisor
  - ls /etc/supervisor/conf.d
  - sudo mv ./controv3rsial.conf /etc/supervisor/conf.d
  - sudo mv ./supervisor_script.sh /home/travis
  - pip install --upgrade pytest
  - sudo supervisorctl reread
  - sudo supervisorctl reload
  - sleep 3
  - sudo supervisorctl status
  - sleep 3
  - ls /usr/bin
  - sudo cat /home/travis/supervisor_out.log
  - sudo cat /home/travis/supervisor_err.log

script: pytest

