language: python
sudo: required
python:
  - 3.6

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - id
  - pwd
  - sudo apt-get install supervisor
  - ls /etc/supervisor/conf.d
  - sudo mv ./controv3rsial.conf /etc/supervisor/conf.d
  - pip install --upgrade pytest
  - sudo supervisorctl reread
  - sudo supervisorctl reload
  - sudo supervisorctl status

script: pytest

