
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: |
            python3 -m venv venv
            pip install --user pytest
            . venv/bin/activate

      # Step 3: Cualquier cosa
      - run:
          name: run tests
          command: |
            echo 'OK' 
      
