version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers

    steps:
      - run: pip install --upgrade pip
      - run: pip install --upgrade pipenv
      - run: pip install --user pytest
      - run: pytest
